#!/sbin/sh

PATH_=$PATH
export PATH=/sbin

mkdir -p /tmp/mnt/cache
mknod /tmp/mtdblock2 b 31 2
mount -t yaffs2 /tmp/mtdblock2 /tmp/mnt/cache

if [ -f /tmp/mnt/cache/recovery/boot ]; then
    RECOVERY_MODE=1
    rm /tmp/mnt/cache/recovery/boot
else
    RECOVERY_MODE=0
fi

umount /tmp/mnt/cache
rm /tmp/mtdblock2


if [ $RECOVERY_MODE = 1 ]; then
    mv /sbin/recovery-ics/init /init
    chown root.root /init
    chmod 750 /init

    mv /sbin/recovery-ics/init.rc /init.rc
    chown root.root /init.rc
    chmod 750 /init.rc

    mkdir /etc
    mv /sbin/recovery-ics/recovery.fstab /etc/recovery.fstab
    chown root.root /etc/recovery.fstab
    chmod 644 /etc/recovery.fstab

    mv /sbin/recovery-ics/ueventd.rc /ueventd.rc
    chown root.root /ueventd.rc
    chmod 644 /ueventd.rc

    mv /sbin/recovery-ics/ueventd.semc.rc /ueventd.semc.rc
    chown root.root /ueventd.semc.rc
    chmod 644 /ueventd.semc.rc

    mv /sbin/recovery-ics/default.prop /default.prop
    chown root.root /default.prop
    chmod 644 /default.prop

    export PATH=$PATH_
    exec /init
fi


mkdir -p /tmp/mnt/system
mknod /tmp/mtdblock0 b 31 0
mount -t yaffs2 /tmp/mtdblock0 /tmp/mnt/system

if [ -f /tmp/mnt/system/framework/SemcGenericUxpRes.apk ]; then
    ROM_TYPE=0
else
    ROM_TYPE=1
fi

umount /tmp/mnt/system
rm /tmp/mtdblock0
rm -rf /tmp/mnt


if [ $ROM_TYPE = 0 ]; then
    mv /sbin/semc-ics/init /init
    chown root.root /init
    chmod 750 /init

    mv /sbin/semc-ics/init.rc /init.rc
    chown root.root /init.rc
    chmod 750 /init.rc

    mv /sbin/semc-ics/init.semc.rc /init.semc.rc
    chown root.root /init.semc.rc
    chmod 750 /init.semc.rc

    mv /sbin/semc-ics/ueventd.rc /ueventd.rc
    chown root.root /ueventd.rc
    chmod 644 /ueventd.rc

    mv /sbin/semc-ics/ueventd.semc.rc /ueventd.semc.rc
    chown root.root /ueventd.semc.rc
    chmod 644 /ueventd.semc.rc

    mv /sbin/semc-ics/default.prop /default.prop
    chown root.root /default.prop
    chmod 644 /default.prop
fi


export PATH=$PATH_
exec /init

